#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/blob/master/examples/yabairc

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# deliberately avoid managing these apps
yabai -m rule --add app='^Dash$' manage=off
yabai -m rule --add app='^VimR$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^CARROTWeather$' manage=off
yabai -m rule --add app='^Dictionary$' manage=off
yabai -m rule --add app='^Things$' manage=off
yabai -m rule --add app='^Messages$' manage=off
yabai -m rule --add app='^Trello$' manage=off
yabai -m rule --add app='^Ripcord$' manage=off
yabai -m rule --add app='^1Password 7$' manage=off
yabai -m rule --add app='^LICEcap 7$' manage=off
yabai -m rule --add app='^Anki$' manage=off
yabai -m rule --add app='^IINA$' manage=off
yabai -m rule --add app='^Monodraw$' manage=off
yabai -m rule --add app='^Tiny Player$' manage=off
yabai -m rule --add app='^Plexamp$' manage=off

echo "yabai configuration loaded.."
