" Name:         RAMS
" Description:  TODO
" Author:       Stefan VanBuren <vanburenstefan@gmail.com>
" Maintainer:   Stefan VanBuren <vanburenstefan@gmail.com>
" Website:      https://svbn.me
" License:      TODO
" Last Updated: Mon Apr 27 20:35:59 2020

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'rams'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#080808', '#ff3d58', '#ff3d58', '#ff3d58',
          \ '#ff3d58', '#ff3d58', '#ff3d58', '#ebebeb', '#080808', '#ff3d58',
          \ '#ff3d58', '#ff3d58', '#ff3d58', '#ff3d58', '#ff3d58', '#ebebeb']
    if has('nvim')
      let g:terminal_color_0 = '#080808'
      let g:terminal_color_1 = '#ff3d58'
      let g:terminal_color_2 = '#ff3d58'
      let g:terminal_color_3 = '#ff3d58'
      let g:terminal_color_4 = '#ff3d58'
      let g:terminal_color_5 = '#ff3d58'
      let g:terminal_color_6 = '#ff3d58'
      let g:terminal_color_7 = '#ebebeb'
      let g:terminal_color_8 = '#080808'
      let g:terminal_color_9 = '#ff3d58'
      let g:terminal_color_10 = '#ff3d58'
      let g:terminal_color_11 = '#ff3d58'
      let g:terminal_color_12 = '#ff3d58'
      let g:terminal_color_13 = '#ff3d58'
      let g:terminal_color_14 = '#ff3d58'
      let g:terminal_color_15 = '#ebebeb'
    endif
    hi Normal guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi ColorColumn guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi CursorColumn guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=#ebebeb guibg=#080808 guisp=NONE gui=reverse cterm=reverse
    hi DiffChange guifg=#ebebeb guibg=#080808 guisp=NONE gui=reverse cterm=reverse
    hi DiffDelete guifg=#ebebeb guibg=#080808 guisp=NONE gui=reverse cterm=reverse
    hi DiffText guifg=#ebebeb guibg=#080808 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi Directory guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi EndOfBuffer guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi ErrorMsg guifg=#ebebeb guibg=#080808 guisp=NONE gui=reverse cterm=reverse
    hi FoldColumn guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#ebebeb guibg=#080808 guisp=NONE gui=italic cterm=italic
    hi IncSearch guifg=#ebebeb guibg=#080808 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi LineNr guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi MatchParen guifg=#ff3d58 guibg=#080808 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi ModeMsg guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi NonText guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Question guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Search guifg=#ebebeb guibg=#080808 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi SignColumn guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=#ff3d58 guibg=#080808 guisp=NONE gui=undercurl cterm=undercurl
    hi SpellCap guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi SpellLocal guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi SpellRare guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi StatusLine guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Substitute guifg=#ff3d58 guibg=#080808 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi TabLine guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Visual guifg=#ebebeb guibg=#080808 guisp=NONE gui=reverse cterm=reverse
    hi VisualNOS guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi WarningMsg guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi WildMenu guifg=#ebebeb guibg=#080808 guisp=NONE gui=NONE cterm=NONE
    hi Comment guifg=#ebebeb guibg=NONE guisp=NONE gui=italic cterm=italic
    hi Constant guifg=#ebebeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Error guifg=#ebebeb guibg=#080808 guisp=NONE gui=reverse cterm=reverse
    hi Identifier guifg=#ebebeb guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Ignore guifg=#ebebeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#ebebeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#ebebeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Statement guifg=#ebebeb guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Todo guifg=#ff3d58 guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
    hi Type guifg=#ebebeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Underlined guifg=#ebebeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
    hi ToolbarLine guifg=NONE guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#ebebeb guibg=#080808 guisp=NONE gui=bold cterm=bold
    hi ALEError guifg=#ff3d58 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi ALEWarning guifg=#ff3d58 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi ALEInfo guifg=#ff3d58 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi ALEErrorSign guifg=#ff3d58 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi ALEWarningSign guifg=#ff3d58 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi ALEInfoSign guifg=#ff3d58 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi! link ExtraWhitespace SpellBad
    if !s:italics
      hi Folded gui=NONE cterm=NONE
      hi Comment gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#53585f', '#ff3100', '#ff3100', '#ff3100',
        \ '#ff3100', '#ff3100', '#ff3100', '#ebebeb', '#53585f', '#ff3100',
        \ '#ff3100', '#ff3100', '#ff3100', '#ff3100', '#ff3100', '#ebebeb']
  if has('nvim')
    let g:terminal_color_0 = '#53585f'
    let g:terminal_color_1 = '#ff3100'
    let g:terminal_color_2 = '#ff3100'
    let g:terminal_color_3 = '#ff3100'
    let g:terminal_color_4 = '#ff3100'
    let g:terminal_color_5 = '#ff3100'
    let g:terminal_color_6 = '#ff3100'
    let g:terminal_color_7 = '#ebebeb'
    let g:terminal_color_8 = '#53585f'
    let g:terminal_color_9 = '#ff3100'
    let g:terminal_color_10 = '#ff3100'
    let g:terminal_color_11 = '#ff3100'
    let g:terminal_color_12 = '#ff3100'
    let g:terminal_color_13 = '#ff3100'
    let g:terminal_color_14 = '#ff3100'
    let g:terminal_color_15 = '#ebebeb'
  endif
  hi Normal guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=#ebebeb guibg=#53585f guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#53585f guibg=#ebebeb guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#53585f guibg=#ebebeb guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#53585f guibg=#ebebeb guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#53585f guibg=#ebebeb guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#53585f guibg=#ebebeb guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#53585f guibg=#ebebeb guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=#53585f guibg=#ebebeb guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi LineNr guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ebebeb guibg=#ff3100 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi ModeMsg guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#53585f guibg=#ebebeb guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi SignColumn guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#ff3100 guibg=#ebebeb guisp=NONE gui=undercurl cterm=undercurl
  hi SpellCap guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi SpellLocal guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi SpellRare guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Substitute guifg=#ff3100 guibg=#ebebeb guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi TabLine guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#53585f guibg=#ebebeb guisp=NONE gui=reverse cterm=reverse
  hi VisualNOS guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#53585f guibg=#ebebeb guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#53585f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#53585f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#53585f guibg=#ebebeb guisp=NONE gui=reverse cterm=reverse
  hi Identifier guifg=#53585f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Ignore guifg=#53585f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#53585f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#53585f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#53585f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Todo guifg=#ff3100 guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
  hi Type guifg=#53585f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#53585f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#53585f guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#53585f guibg=#ebebeb guisp=NONE gui=bold cterm=bold
  hi ALEError guifg=#ff3100 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ALEWarning guifg=#ff3100 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ALEInfo guifg=#ff3100 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ALEErrorSign guifg=#ff3100 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#ff3100 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#ff3100 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ExtraWhitespace SpellBad
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Normal ctermfg=255 ctermbg=232 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=255 ctermbg=232 cterm=NONE
    hi ColorColumn ctermfg=255 ctermbg=232 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=255 ctermbg=232 cterm=NONE
    hi CursorColumn ctermfg=255 ctermbg=232 cterm=NONE
    hi CursorLine ctermfg=255 ctermbg=232 cterm=NONE
    hi CursorLineNr ctermfg=255 ctermbg=232 cterm=NONE
    hi DiffAdd ctermfg=255 ctermbg=232 cterm=reverse
    hi DiffChange ctermfg=255 ctermbg=232 cterm=reverse
    hi DiffDelete ctermfg=255 ctermbg=232 cterm=reverse
    hi DiffText ctermfg=255 ctermbg=232 cterm=bold,reverse
    hi Directory ctermfg=255 ctermbg=232 cterm=NONE
    hi EndOfBuffer ctermfg=255 ctermbg=232 cterm=NONE
    hi ErrorMsg ctermfg=255 ctermbg=232 cterm=reverse
    hi FoldColumn ctermfg=255 ctermbg=232 cterm=NONE
    hi Folded ctermfg=255 ctermbg=232 cterm=italic
    hi IncSearch ctermfg=255 ctermbg=232 cterm=bold,reverse
    hi LineNr ctermfg=255 ctermbg=232 cterm=NONE
    hi MatchParen ctermfg=203 ctermbg=232 cterm=bold,reverse
    hi ModeMsg ctermfg=255 ctermbg=232 cterm=NONE
    hi MoreMsg ctermfg=255 ctermbg=232 cterm=NONE
    hi NonText ctermfg=255 ctermbg=232 cterm=NONE
    hi Pmenu ctermfg=255 ctermbg=232 cterm=NONE
    hi PmenuSbar ctermfg=255 ctermbg=232 cterm=NONE
    hi PmenuSel ctermfg=255 ctermbg=232 cterm=NONE
    hi PmenuThumb ctermfg=255 ctermbg=232 cterm=NONE
    hi Question ctermfg=255 ctermbg=232 cterm=NONE
    hi Search ctermfg=255 ctermbg=232 cterm=bold,reverse
    hi SignColumn ctermfg=255 ctermbg=232 cterm=NONE
    hi SpecialKey ctermfg=255 ctermbg=232 cterm=NONE
    hi SpellBad ctermfg=203 ctermbg=232 cterm=undercurl
    hi SpellCap ctermfg=255 ctermbg=232 cterm=NONE
    hi SpellLocal ctermfg=255 ctermbg=232 cterm=NONE
    hi SpellRare ctermfg=255 ctermbg=232 cterm=NONE
    hi StatusLine ctermfg=255 ctermbg=232 cterm=NONE
    hi StatusLineNC ctermfg=255 ctermbg=232 cterm=NONE
    hi Substitute ctermfg=203 ctermbg=232 cterm=bold,reverse
    hi TabLine ctermfg=255 ctermbg=232 cterm=NONE
    hi TabLineFill ctermfg=255 ctermbg=232 cterm=NONE
    hi TabLineSel ctermfg=255 ctermbg=232 cterm=NONE
    hi Title ctermfg=255 ctermbg=232 cterm=NONE
    hi VertSplit ctermfg=255 ctermbg=232 cterm=NONE
    hi Visual ctermfg=255 ctermbg=232 cterm=reverse
    hi VisualNOS ctermfg=255 ctermbg=232 cterm=NONE
    hi WarningMsg ctermfg=255 ctermbg=232 cterm=NONE
    hi WildMenu ctermfg=255 ctermbg=232 cterm=NONE
    hi Comment ctermfg=255 ctermbg=NONE cterm=italic
    hi Constant ctermfg=255 ctermbg=NONE cterm=NONE
    hi Error ctermfg=255 ctermbg=232 cterm=reverse
    hi Identifier ctermfg=255 ctermbg=NONE cterm=bold
    hi Ignore ctermfg=255 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=255 ctermbg=NONE cterm=NONE
    hi Special ctermfg=255 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=255 ctermbg=NONE cterm=bold
    hi Todo ctermfg=203 ctermbg=NONE cterm=bold,underline
    hi Type ctermfg=255 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=255 ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=255 cterm=NONE
    hi ToolbarButton ctermfg=255 ctermbg=232 cterm=bold
    hi ALEError ctermfg=203 ctermbg=NONE cterm=underline
    hi ALEWarning ctermfg=203 ctermbg=NONE cterm=underline
    hi ALEInfo ctermfg=203 ctermbg=NONE cterm=underline
    hi ALEErrorSign ctermfg=203 ctermbg=NONE cterm=NONE
    hi ALEWarningSign ctermfg=203 ctermbg=NONE cterm=NONE
    hi ALEInfoSign ctermfg=203 ctermbg=NONE cterm=NONE
    hi! link ExtraWhitespace SpellBad
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Normal ctermfg=240 ctermbg=255 cterm=NONE
  hi Terminal ctermfg=240 ctermbg=255 cterm=NONE
  hi ColorColumn ctermfg=255 ctermbg=240 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=240 ctermbg=255 cterm=NONE
  hi CursorColumn ctermfg=240 ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=240 ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=240 ctermbg=255 cterm=NONE
  hi DiffAdd ctermfg=240 ctermbg=255 cterm=reverse
  hi DiffChange ctermfg=240 ctermbg=255 cterm=reverse
  hi DiffDelete ctermfg=240 ctermbg=255 cterm=reverse
  hi DiffText ctermfg=240 ctermbg=255 cterm=bold,reverse
  hi Directory ctermfg=240 ctermbg=255 cterm=NONE
  hi EndOfBuffer ctermfg=240 ctermbg=255 cterm=NONE
  hi ErrorMsg ctermfg=240 ctermbg=255 cterm=reverse
  hi FoldColumn ctermfg=240 ctermbg=255 cterm=NONE
  hi Folded ctermfg=240 ctermbg=255 cterm=italic
  hi IncSearch ctermfg=240 ctermbg=255 cterm=bold,reverse
  hi LineNr ctermfg=240 ctermbg=255 cterm=NONE
  hi MatchParen ctermfg=255 ctermbg=196 cterm=bold,reverse
  hi ModeMsg ctermfg=240 ctermbg=255 cterm=NONE
  hi MoreMsg ctermfg=240 ctermbg=255 cterm=NONE
  hi NonText ctermfg=240 ctermbg=255 cterm=NONE
  hi Pmenu ctermfg=240 ctermbg=255 cterm=NONE
  hi PmenuSbar ctermfg=240 ctermbg=255 cterm=NONE
  hi PmenuSel ctermfg=240 ctermbg=255 cterm=NONE
  hi PmenuThumb ctermfg=240 ctermbg=255 cterm=NONE
  hi Question ctermfg=240 ctermbg=255 cterm=NONE
  hi Search ctermfg=240 ctermbg=255 cterm=bold,reverse
  hi SignColumn ctermfg=240 ctermbg=255 cterm=NONE
  hi SpecialKey ctermfg=240 ctermbg=255 cterm=NONE
  hi SpellBad ctermfg=196 ctermbg=255 cterm=undercurl
  hi SpellCap ctermfg=240 ctermbg=255 cterm=NONE
  hi SpellLocal ctermfg=240 ctermbg=255 cterm=NONE
  hi SpellRare ctermfg=240 ctermbg=255 cterm=NONE
  hi StatusLine ctermfg=240 ctermbg=255 cterm=NONE
  hi StatusLineNC ctermfg=240 ctermbg=255 cterm=NONE
  hi Substitute ctermfg=196 ctermbg=255 cterm=bold,reverse
  hi TabLine ctermfg=240 ctermbg=255 cterm=NONE
  hi TabLineFill ctermfg=240 ctermbg=255 cterm=NONE
  hi TabLineSel ctermfg=240 ctermbg=255 cterm=NONE
  hi Title ctermfg=240 ctermbg=255 cterm=NONE
  hi VertSplit ctermfg=240 ctermbg=255 cterm=NONE
  hi Visual ctermfg=240 ctermbg=255 cterm=reverse
  hi VisualNOS ctermfg=240 ctermbg=255 cterm=NONE
  hi WarningMsg ctermfg=240 ctermbg=255 cterm=NONE
  hi WildMenu ctermfg=240 ctermbg=255 cterm=NONE
  hi Comment ctermfg=240 ctermbg=NONE cterm=italic
  hi Constant ctermfg=240 ctermbg=NONE cterm=NONE
  hi Error ctermfg=240 ctermbg=255 cterm=reverse
  hi Identifier ctermfg=240 ctermbg=NONE cterm=bold
  hi Ignore ctermfg=240 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=240 ctermbg=NONE cterm=NONE
  hi Special ctermfg=240 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=240 ctermbg=NONE cterm=bold
  hi Todo ctermfg=196 ctermbg=NONE cterm=bold,underline
  hi Type ctermfg=240 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=240 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=240 cterm=NONE
  hi ToolbarButton ctermfg=240 ctermbg=255 cterm=bold
  hi ALEError ctermfg=196 ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=196 ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=196 ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=196 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=196 ctermbg=NONE cterm=NONE
  hi ALEInfoSign ctermfg=196 ctermbg=NONE cterm=NONE
  hi! link ExtraWhitespace SpellBad
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=NONE ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=NONE ctermbg=NONE cterm=reverse
    hi DiffText ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=reverse
    hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Folded ctermfg=NONE ctermbg=NONE cterm=italic
    hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi LineNr ctermfg=NONE ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi NonText ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=NONE ctermbg=NONE cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
    hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Question ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Search ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Substitute ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi TabLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
    hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Title ctermfg=NONE ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
    hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Comment ctermfg=NONE ctermbg=NONE cterm=italic
    hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Error ctermfg=NONE ctermbg=NONE cterm=reverse
    hi Identifier ctermfg=NONE ctermbg=NONE cterm=bold
    hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Special ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Statement ctermfg=NONE ctermbg=NONE cterm=bold
    hi Todo ctermfg=NONE ctermbg=NONE cterm=bold,underline
    hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold
    hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEErrorSign ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ALEWarningSign ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ALEInfoSign ctermfg=NONE ctermbg=NONE cterm=NONE
    hi! link ExtraWhitespace SpellBad
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Terminal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=reverse
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=NONE ctermbg=NONE cterm=italic
  hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi LineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Substitute ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi TabLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Title ctermfg=NONE ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Comment ctermfg=NONE ctermbg=NONE cterm=italic
  hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Identifier ctermfg=NONE ctermbg=NONE cterm=bold
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Special ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Statement ctermfg=NONE ctermbg=NONE cterm=bold
  hi Todo ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEInfoSign ctermfg=NONE ctermbg=NONE cterm=NONE
  hi! link ExtraWhitespace SpellBad
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                rgb(  8,   8,   8)     ~        none
" Color: accent               rgb(255,  61,  88)     ~        none
" Color: white                rgb(235, 235, 235)     ~        none
" Term colors: black accent accent accent accent accent accent white
" Term colors: black accent accent accent accent accent accent white
" Background: light
" Color: black                rgb( 83,  88,  95)     ~        none
" Color: accent               rgb(255,  49,   0)     ~        none
" Color: white                rgb(235, 235, 235)     ~        none
" Term colors: black accent accent accent accent accent accent white
" Term colors: black accent accent accent accent accent accent white
" Background: any
" vim: et ts=2 sw=2
