# https://starship.rs/config

# https://starship.rs/config/#character
[character]
success_symbol = "[;](bold white)"
error_symbol = "[×](bold red)"
vimcmd_symbol = "[;](bold red)"

# https://starship.rs/config/#git-branch
[git_branch]
symbol = ""
style = "white"

# https://starship.rs/config/#git-status
[git_status]
style = "white"
deleted = "×"
format = "[$all_status$ahead_behind]($style) "
# this is still quite slow for not much gain
disabled = true

# https://starship.rs/config/#directory
[directory]
style = "white"

# https://starship.rs/config/#package-version
[package]
disabled = true

# https://starship.rs/config/#command-duration
[cmd_duration]
disabled = true

# https://starship.rs/config/#google-cloud-gcloud
[gcloud]
disabled = true

# https://starship.rs/config/#go
[golang]
disabled = true

# https://starship.rs/config/#buf
[buf]
disabled = true

# https://starship.rs/config/#jobs
[jobs]
# This might be useful, but something is always starting a job in kitty?
disabled = true
